# Generated by Django 2.1.2 on 2018-10-25 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0002_auto_20181024_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_settings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
