# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0012_auto_20170822_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.SlugField(unique=True, verbose_name='component alias')),
                ('settings_json', models.TextField(blank=True, default='{}', null=True)),
            ],
            options={
                'verbose_name_plural': 'configs',
                'verbose_name': 'config',
            },
        ),
    ]
