# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0014_auto_20170822_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation datetime'),
        ),
        migrations.AlterField(
            model_name='component',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modification datetime'),
        ),
    ]
