# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0015_auto_20170822_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='environment',
            field=models.SlugField(default='base', verbose_name='environment alias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='component',
            field=models.SlugField(verbose_name='component alias'),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together=set([('component', 'environment')]),
        ),
    ]
