# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0017_auto_20170822_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='settings_json',
            new_name='data',
        ),
    ]
