# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0019_auto_20170823_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name',), 'permissions': (('view_components', 'Can view component'),), 'verbose_name': 'component', 'verbose_name_plural': 'components'},
        ),
    ]
