# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0021_logentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='action_time',
        ),
        migrations.AddField(
            model_name='logentry',
            name='action_type',
            field=models.CharField(blank=True, choices=[('create', 'create'), ('update', 'update'), ('delete', 'delete')], db_index=True, max_length=128, null=True, verbose_name='action type'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='action time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(max_length=255, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='new_data_json',
            field=models.TextField(blank=True, null=True, verbose_name='new data JSON'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='old_data_json',
            field=models.TextField(blank=True, null=True, verbose_name='old data JSON'),
        ),
    ]
