# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0022_auto_20170915_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='new_data_json',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='old_data_json',
        ),
        migrations.AddField(
            model_name='logentry',
            name='_new_data',
            field=models.TextField(blank=True, db_column='new_data', null=True, verbose_name='new data'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='_old_data',
            field=models.TextField(blank=True, db_column='old_data', null=True, verbose_name='old data'),
        ),
    ]
