# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0023_auto_20170915_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='settings_json',
        ),
    ]
