# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0024_remove_component_settings_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='_new_data',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='_old_data',
        ),
        migrations.AddField(
            model_name='logentry',
            name='new_data_json',
            field=models.TextField(blank=True, null=True, verbose_name='new data'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='old_data_json',
            field=models.TextField(blank=True, null=True, verbose_name='old data'),
        ),
    ]
