# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0025_auto_20170916_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='settings_json',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
