# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 06:45
from django.db import migrations

from configfactory.utils import json


def create_config_db_store(apps, schema_editor):

    Component = apps.get_model('configfactory', 'Component')
    Config = apps.get_model('configfactory', 'Config')
    Environment = apps.get_model('configfactory', 'Environment')

    environments = Environment.objects.all()

    for component in Component.objects.all():
        settings = json.loads(component.settings_json)

        for environment in environments:
            config, created = Config.objects.get_or_create(
                component=component.alias,
                environment=environment.alias
            )
            config.data = json.dumps(
                settings.get(environment.alias, {})
            )
            config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0026_component_settings_json'),
    ]

    operations = [
        migrations.RunPython(
            code=create_config_db_store,
            reverse_code=migrations.RunPython.noop
        ),
    ]
