# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0027_auto_20170918_0645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ('name',), 'permissions': (('view_component', 'Can view component'),), 'verbose_name': 'component', 'verbose_name_plural': 'components'},
        ),
    ]
