# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0028_auto_20170918_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='additional_props',
            field=models.BooleanField(default=True, help_text='Any additional properties are allowed'),
        ),
    ]
