# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


def set_user_email(apps, schema_editor):

    User = apps.get_model('configfactory', 'User')

    for user in User.objects.filter(email=''):
        user.email = '{username}@mail.com'.format(
            username=user.username,
        )
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0029_component_additional_props'),
    ]

    operations = [
        migrations.RunPython(
            code=set_user_email,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
