# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0030_auto_20170924_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='additional_props',
        ),
        migrations.AddField(
            model_name='component',
            name='strict_keys',
            field=models.BooleanField(default=False, help_text='Deny to change keys schema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
