# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0031_auto_20170928_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environments_json', models.TextField(default='[]')),
                ('components_json', models.TextField(default='[]')),
                ('configs_json', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'backup',
                'verbose_name_plural': 'backups',
                'ordering': ('created_at',),
            },
        ),
    ]
