# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0032_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comment'),
        ),
    ]
