# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0033_backup_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'ordering': ('-created_at',), 'verbose_name': 'backup', 'verbose_name_plural': 'backups'},
        ),
    ]
