# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0034_auto_20171002_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='components_json',
            new_name='components_data',
        ),
        migrations.RenameField(
            model_name='backup',
            old_name='configs_json',
            new_name='configs_data',
        ),
        migrations.RenameField(
            model_name='backup',
            old_name='environments_json',
            new_name='environments_data',
        ),
    ]
