# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0035_auto_20171003_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='fallback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='configfactory.Environment', verbose_name='fallback environment'),
        ),
    ]
