# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0036_auto_20171029_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this environment should be treated as active. Unselect this instead of deleting environments.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this environment should be treated as active. Unselect this instead of deleting environments.', verbose_name='active'),
        ),
    ]
