# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0037_auto_20171029_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this component should be treated as active. Unselect this instead of deleting components.', verbose_name='active'),
        ),
    ]
