# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('configfactory', '0038_auto_20171029_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=48, unique=True, verbose_name='Token')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'api settings',
                'verbose_name_plural': 'api settings',
            },
        ),
    ]
