# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0039_apisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_settings', to='auth.Group', verbose_name='group'),
        ),
    ]
