# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0040_auto_20171029_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether this group is enabled for API.', verbose_name='enabled'),
        ),
    ]
