# Generated by Django 2.0.2 on 2018-05-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0042_auto_20180515_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='data_file',
            field=models.FileField(upload_to='backups'),
        ),
    ]
