# Generated by Django 2.0.2 on 2018-05-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configfactory', '0043_auto_20180515_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='components_data',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='configs_data',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='environments_data',
        ),
    ]
